# https://help.github.com/en/actions

name: server

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Prepare configs
        run: |
          sed -ri \
            -e 's!^(\s*CustomLog)\s+\S+!\1 /proc/self/fd/1!g' \
            -e 's!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g' \
            -e 's!^(\s*TransferLog)\s+\S+!\1 /proc/self/fd/1!g' \
            "httpd.conf"

      - name: Test with server-configs-test
        uses: h5bp/server-configs-test@6.0.0
        with:
          command: test
          server: httpd
          root-path: /usr/local/apache2/htdocs
          certs-path: /usr/local/apache2/certs
          configs-volumes: test/vhosts:/usr/local/apache2/vhosts;h5bp:/usr/local/apache2/h5bp;httpd.conf:/usr/local/apache2/conf/httpd.conf
          tests: basic-file-access;caching;cache-busting;custom-errors;forbidden-files;enforce-gzip;precompressed-files-gzip;rewrites;ssl

      - name: Benchmark
        uses: h5bp/server-configs-test@6.0.0
        with:
          command: benchmark
          server: httpd
          root-path: /usr/local/apache2/htdocs
          certs-path: /usr/local/apache2/certs
          configs-volumes: test/vhosts:/usr/local/apache2/vhosts;h5bp:/usr/local/apache2/h5bp;httpd.conf:/usr/local/apache2/conf/httpd.conf
